---
title: "Indomethacin for the Prevention of Post-ERCP Pancreatitis Dataset Description Document"
author: "Peter Higgins"
date: "8/10/2021"
output: 
  html_document:
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Source: 
This data set is provided by B. Joseph Elmunzer, the primary author of a study published on 2012 in the New England Journal of Medicine, volume 366, pages 1414-1422.

 Presented are the results of a randomized, placebo-controlled, prospective 2-arm trial of indomethacin 100 mg PR once vs. placebo to prevent post-ERCP Pancreatitis in 602 patients. 
 
### Background
ERCP, or endoscopic retrograde cholangio-pancreatogram, is a procedure performed by threading an endoscope through the mouth to the opening in the duodenum where bile and pancreatic digestive juices are released into the intestine. ERCP is helpful for treating blockages of flow of bile (gallstones, cancer), or diagnosing cancers of the pancreas, but has a high rate of complications (15-25%). 

The occurrence of post-ERCP pancreatitis is a common and feared complication, as pancreatitis can result in multisystem organ failure and death, and can occur in ~ 16% of ERCP procedures. 

The inflammatory cytokine storm that can result from this procedural complication can be quite severe. Several small randomized trials suggested that anti-inflammatory NSAID therapies at the time of ERCP could reduce the rate of this complication, but all were rather small single-center studies, and were not sufficiently convincing to change practice. 

Elmunzer, Higgins, and colleagues performed a meta-analysis of these small trials, which suggested that this was a significant effect, and that indomethacin could result in a 64% reduction in post-ERCP pancreatitis. 

The investigators took this as a possible over-estimate of the effect (due to publication bias), and designed a multicenter RCT of a planned 948 patients to see a reduction of 50% from a placebo rate of 10% to an indomethacin rate of 5%. Two interim analyses were performed, after 400 and 600 patients were enrolled, using an alpha spending function. The Data and Safety Monitoring Board stopped the study after 602 participants were enrolled because of the significantly positive effect of indomethacin, which reduced post-ERCP pancreatitis from 16.9% in the placebo group to 9.2% in the indomethacin group. 
You can find the manuscript at [Indomethacin to Prevent Post-ERCP Pancreatitis](https://www.nejm.org/doi/full/10.1056/NEJMoa1111103).
 
### Abstract

 This data set contains baseline characteristics and outcomes for 602 participants at increased risk of post-ERCP pancreatitis at 4 centers. At the time of this trial, pancreatic stenting was the only effective therapy to reduce post-ERCP pancreatitis (PEP), and previous anti-inflammatory therapies had largely proved ineffective. This randomized clinical trial was inspired by a [meta-analysis](https://pubmed.ncbi.nlm.nih.gov/18375470/) of several small trials that suggested that indomethacin could be effective. PEP was a common complication after ERCP, with rates of 15-25%, and resulting in hospitalization, multisystem organ failure, and occasional deaths. This treatment proved to be effective, leading the DSMB to halt enrollment after 602 of a planned 948 participants were enrolled. The use of rectal indomethacin is now the standard of care for high-risk ERCP, and led generic manufacturers to [increase the price](https://pubmed.ncbi.nlm.nih.gov/32150228/) of generic indomethacin suppositories from 1 USD per dose to over $300.

### Study Design

Prospective, Randomized, Multicenter Placebo-Controlled Clinical Trial

### Subjects & Variables

602 participants undergoing ERCP who were at elevated risk of post-ERCP pancratitis were assigned to 1 of 2 treatments:

- Indomethacin 100 mg suppository x 1 at the time of ERCP
- Placebo

### Variables

- id
- site
- age
- risk
- gender
- outcome
- sod
- pep
- recpanc
- psphinc
- precut
- difcan
- pneudil
- amp
- paninj
- acinar
- brush
- asa81
- asa325
- asa
- prophystent
- therastent
- pdstent
- sodsom
- bsphinc
- bstent
- chole
- pbmal
- train
- status
- type
- rx
- bleed

#### Citation(s)

Elmunzer, Higgins, et al., _A Randomized Trial of Rectal Indomethacin to Prevent Post-ERCP Pancreatitis_, New England Journal of Medicine, 2012, volume 366, pages 1414-1422, as found [here](https://www.nejm.org/doi/full/10.1056/NEJMoa1111103).

