---
title: "Streptomycin for TB Dataset Description Document"
author: "Peter Higgins"
date: "6/25/2021"
output: 
  pdf_document: default
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Streptomycin for Tuberculosis Dataset Introduction and Description

Source: This data set is reconstructed from a study published on October 30, 1948 in the British Medical Journal, reported by the Tuberculosis Trials Committee of the MRC. The baseline characteristics and endpoints were re-created for each of the 107 participants based on Tables 1-4 in the manuscript. All 4 tables can be exactly reproduced from this dataset.

 Presented are the results of a randomized, placebo-controlled, prospective 2-arm trial of streptomycin 2 grams daily (Streptomycin) vs. placebo (Control) to treat tuberculosis in 107 young patients. 
 
 The Streptomycin for Tuberculosis trial in 1948 is considered the first modern randomized, placebo-controlled clinical trial, which could be done in part because there were very limited supplies of streptomycin in the UK after World War II. The randomized trial was helpful to prevent rationing and black market selling of streptomycin, and helped with allocation of limited hospital isolation beds for bedrest therapy (the control arm, and standard of care at the time).
 
 This publication seems a bit primitive today, without standard features like a proper Table 1, and some creative use of graphs to display baseline characteristics of the study sample. The authors were publishing the first formal RCT, and had no modern CONSORT standards to go by. Their Table 1 is essentially three 2xN tables pasted together horizontally.
 
 More strikingly, there is no ethics committee approval, nor any consent, which is consistent with practices in 1948. You can read the pdf of the original journal article at [Streptomycin in TB Study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2091872/pdf/brmedj03701-0007.pdf). This was the first of a series of 3 trials, in which the initial effectiveness of Streptomycin was established, but rapid streptomycin resistance developed, and significant side effects occurred at a dose of 2 grams of streptomycin. This type of resistance also occurred with another new anti-tubercular therapy at the time, PAS (Para-Amino-Salicylate). 
 
 Subsequent trials B and C evaluated different doses and combinations of Streptomycin and PAS, and these were published together in 1952 in the BMJ, with the pdf available here [1952 Three Streptomycin in TB Studies Summarized](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2023677/pdf/brmedj03496-0024.pdf).
 
 Commentary on the conduct of these seminal trials from one of the MD investigators can be found at [MD Clinical Trialist Commentary](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1592068/). Commentary on the design and analysis of these trials from statistician A. Bradford Hill can be found at [Statistican Commentary](https://www.sciencedirect.com/science/article/abs/pii/019724569090001I).
 
#### Abstract

 This data set contains reconstructed records of 107 participants with pulmonary tuberculosis. In 1948, collapse therapy (collapsing the lung by puncturing it with a needle) and bedrest in sanitariums were the standard of care. This is the first modern report of a randomized clinical trial. While patients on streptomycin often improved rapidly, streptomycin resistance developed, and many participants relapsed. There was still a significant difference in the death rate between the two arms. A similar effect was seen with PAS, another new therapy for tuberculosis, and the authors rapidly figured out that combination therapy was needed, which was tested in two subsequent trials, which were published in 1952.

#### Study Design

Prospective, Randomized, Multicenter Placebo-Controlled Clinical Trial

### Subjects & Variables

107 participants with pulmonary tuberculosis were assigned to 1 of 2 treatments:

- Streptomycin 2 g by mouth daily
- Control therapy - bed rest

### Variables

- patient_id
- arm
- dose_strep_g
- dose_PAS_g
- gender
- baseline_condition
- baseline_temp
- baseline_esr
- baseline_cavitation
- strep_resistance
- radiologic_6m
- rad_num
- improved

#### Citation(s)

The Streptomycin in Tuberculosis Trials Committee, _Streptomycin Treatment of Pulmonary Tuberculosis_, British Medical Journal, October 30, 1948, pages 769-782, as found [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2091872/pdf/brmedj03701-0007.pdf).

