---
title: "Prostate blood storage codebook"
author: "Peter Higgins"
date: "10/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Blood Storage Dataset Introduction and Codebook

Source: This data set is from the Teaching of Statistics in the Health Sciences (TSHS) resources portal at:  
https://www.causeweb.org/tshs/category/dataset/

The Blood Storage dataset was contributed by Dr. Amy Nowacki, Associate Professor, Cleveland Clinic. Please refer to this resource as: Amy S. Nowacki, “Blood Storage Dataset”, TSHS Resources Portal (2017). 

#### Abstract

 This data set contains 316 men who had undergone radical prostatectomy and received transfusion during or within 30 days of the surgical procedure and had available PSA follow-up data. The main exposure of interest was RBC storage duration group. A number of demographic, baseline and prognostic factors were also collected. The outcome was time to biochemical cancer recurrence. The dataset is cleaned and complete. There are no outliers or data problems. These are data from a study by Cata et al. “Blood Storage Duration and Biochemical Recurrence of Cancer after Radical Prostatectomy”. Mayo Clin Proc 2011; 86(2): 120-127.

#### Background

Prostate cancer is the most common malignant neoplasm in men, and radical prostatectomy is among the primary therapies for localized prostate cancer. The biochemical recurrence-free survival rate 5 years after prostatectomy ranges from 70% to 90%. Improvements in the surgical technique have decreased the amount of intraoperative blood loss occurring during radical prostatectomy; however, substantial numbers of patients still require perioperative blood transfusions.
Blood transfusions are associated with adverse reactions, including postoperative infections and transfusion-related immune perturbations. Allogeneic leukocytes present in the transfused blood are thought to suppress host cellular immune responses. Furthermore, the immunodepressant effect is secondary to an imbalance of accumulated cytokines and proinflammatory mediators in the transfused blood against decreased production of lymphocyte stimulating cell-mediated cytokines, such as interleukin 2 and increased release of immunosuppressive prostaglandins in the patient undergoing transfusion.
In cancer patients, perioperative blood transfusion has long been suspected of reducing long-term survival, but available evidence is inconsistent. It is also unclear which components of transfused blood underlie the cancer-promoting effects reported by some studies. An important factor associated with the deleterious effects of blood transfusion is the storage age of the transfused blood units. It is suspected that cancer recurrence may be worsened after the transfusion of older blood.

#### Study Objective
This study evaluated the association between red blood cells (RBC) storage duration and biochemical prostate cancer recurrence after radical prostatectomy. Specifically, tested was the hypothesis that perioperative transfusion of allogeneic RBCs stored for a prolonged period is associated with earlier biochemical recurrence of prostate cancer after prostatectomy.

#### Study Design

Retrospective Cohort Study

#### Subjects & Variables

Patients were assigned to 1 of 3 RBC age exposure groups on the basis of the terciles (ie, the 33rd and 66th percentiles) of the overall distribution of RBC storage duration if all their transfused units could be loosely characterized as of “younger,” “middle,” or “older” age. Although this approach resulted in the removal of certain patients with wide RBC age distributions, it has the advantage of defining an essentially random and clearly separable exposure.
Prostate-specific antigen (PSA) was used as a biochemical marker of prostate cancer recurrence after prostatectomy. A PSA value of at least 0.4 ng/mL (to convert to μg/L, multiply by 1.0) followed by another increase was considered biochemical cancer recurrence.
The initial population consisted of 865 men who had undergone radical prostatectomy and received transfusion during or within 30 days of the surgical procedure at Cleveland Clinic and had available PSA follow-up data. Of these patients, 110 were excluded from the analysis because they received a combination of allogeneic and autologous blood products. Of the remaining 755 patients, 405 (54%) received solely allogeneic and 350 patients (46%) received solely autologous RBC units. Of the 405 patients who received allogeneic RBC transfusion, 89 were excluded because their transfused RBC age distribution included more than one of the terciles. Thus, this dataset consists of the 316 patients who received solely allogeneic blood products and could be classified into an RBC age exposure group.

N = 316 subjects 
20 variables

#### Citation(s)

Cata et al. “Blood Storage Duration and Biochemical Recurrence of Cancer after Radical Prostatectomy”. _Mayo Clinic Proceedings_ 2011; 86(2): 120-127.

### Codebook

|Position| Variable| Variable Label| Units| Value Codes|
|--------|---------|---------------|------| ---------|
|1| RBC Age Group|RBC storage duration group||1 = ≤ 13 days (Younger)<br>2 = 13 - 18 days (Middle)<br>3 = ≥18 days (Older)|
|2|Median RBC Age|Median RBC age of all transfused units within each group|days||
|3|Age|Patient age|years||
|4|AA|African American race||0 = non-African American<br>1 = African American|
|5|FamHx|Family history of disease||0 = No<br>1 = Yes|
|6|PVol|Prostate Volume|g||
|7|TVol|Tumor Volume||1 = Low<br>2 = Medium<br>3 = Extensive|
|8|T Stage|Clinical T Category||1 = stage T1-T2a<br>2 = stage T2b-T3|
|9|bGS|Biopsy Gleason Score||1 = score 0-6<br>2 = score 7<br>3 = score 8-10|
|10|BN+|Bladder neck positive||0 = No<br>1= Yes|
|11|OrganConfined|Organ confined||0 = No<br>1= Yes|
|12|PreopPSA|Preoperative prostate specific antigen (PSA)|ng/mL||
|13|PreopTherapy|Preoperative Therapy||0 = No<br>1= Yes|
|14|Units|Number of allogeneic units|||
|15|sGS|Surgical Gleason Score||1 = Not assigned<br>2 = No residual disease or score 0-6<br>3 = score 7<br>4 = score 8-10|
|16|AnyAdjTherapy|Any adjuvant therapy||0 = No<br>1= Yes|
|17|AdjRadTherapy|Adjuvant radiation therapy||0 = No<br>1= Yes|
|18|Recurrence|Biochemical recurrence of prostate cancer||0 = No recurrence|
|19|Censor|Censoring indicator||0 = Not censored|
|20|TimeToRecurrence|Time to biochemical recurrence of prostate cancer|months||