# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# these examples from github r-lib/github-actions
# https://github.com/r-lib/actions

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
    # set up R
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2' # The R version to download (if necessary) and use.

    # set up R dependencies
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        extra-packages: |
          any::rmarkdown
          any::rcmdcheck
        needs: |
          website
          coverage

# set up pandoc
    - uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: '2.17.1' # The pandoc version to download (if necessary) and use.
    - run: echo "# Test" | pandoc -t html

# set up tinytex
    - uses: r-lib/actions/setup-tinytex@v2
    - run: tlmgr --version

# run r-cmd-check
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
    - uses: r-lib/actions/check-r-package@v2
      with:
       args: 'c("--no-manual", "--as-cran")'
       error-on: '"error"'
       check-dir: '"check"'
